spring:
  application:
    name: kafka-course
---
spring:
  kafka:
    topic: topic-course-1
---
spring:
  kafka:
    producer:
      boostrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer