/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.kafka.course.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class EventMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -305770136598820586L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EventMessage\",\"namespace\":\"com.kafka.course.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"messageEventType\",\"type\":{\"type\":\"record\",\"name\":\"MessageEventType\",\"fields\":[{\"name\":\"message\",\"type\":\"string\"},{\"name\":\"addressee\",\"type\":\"string\"},{\"name\":\"sender\",\"type\":\"string\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EventMessage> ENCODER =
      new BinaryMessageEncoder<EventMessage>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EventMessage> DECODER =
      new BinaryMessageDecoder<EventMessage>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<EventMessage> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<EventMessage> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EventMessage>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this EventMessage to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a EventMessage from a ByteBuffer. */
  public static EventMessage fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int id;
  @Deprecated public com.kafka.course.avro.MessageEventType messageEventType;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EventMessage() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param messageEventType The new value for messageEventType
   */
  public EventMessage(java.lang.Integer id, com.kafka.course.avro.MessageEventType messageEventType) {
    this.id = id;
    this.messageEventType = messageEventType;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return messageEventType;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: messageEventType = (com.kafka.course.avro.MessageEventType)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'messageEventType' field.
   * @return The value of the 'messageEventType' field.
   */
  public com.kafka.course.avro.MessageEventType getMessageEventType() {
    return messageEventType;
  }

  /**
   * Sets the value of the 'messageEventType' field.
   * @param value the value to set.
   */
  public void setMessageEventType(com.kafka.course.avro.MessageEventType value) {
    this.messageEventType = value;
  }

  /**
   * Creates a new EventMessage RecordBuilder.
   * @return A new EventMessage RecordBuilder
   */
  public static com.kafka.course.avro.EventMessage.Builder newBuilder() {
    return new com.kafka.course.avro.EventMessage.Builder();
  }

  /**
   * Creates a new EventMessage RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EventMessage RecordBuilder
   */
  public static com.kafka.course.avro.EventMessage.Builder newBuilder(com.kafka.course.avro.EventMessage.Builder other) {
    return new com.kafka.course.avro.EventMessage.Builder(other);
  }

  /**
   * Creates a new EventMessage RecordBuilder by copying an existing EventMessage instance.
   * @param other The existing instance to copy.
   * @return A new EventMessage RecordBuilder
   */
  public static com.kafka.course.avro.EventMessage.Builder newBuilder(com.kafka.course.avro.EventMessage other) {
    return new com.kafka.course.avro.EventMessage.Builder(other);
  }

  /**
   * RecordBuilder for EventMessage instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EventMessage>
    implements org.apache.avro.data.RecordBuilder<EventMessage> {

    private int id;
    private com.kafka.course.avro.MessageEventType messageEventType;
    private com.kafka.course.avro.MessageEventType.Builder messageEventTypeBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.kafka.course.avro.EventMessage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.messageEventType)) {
        this.messageEventType = data().deepCopy(fields()[1].schema(), other.messageEventType);
        fieldSetFlags()[1] = true;
      }
      if (other.hasMessageEventTypeBuilder()) {
        this.messageEventTypeBuilder = com.kafka.course.avro.MessageEventType.newBuilder(other.getMessageEventTypeBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing EventMessage instance
     * @param other The existing instance to copy.
     */
    private Builder(com.kafka.course.avro.EventMessage other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.messageEventType)) {
        this.messageEventType = data().deepCopy(fields()[1].schema(), other.messageEventType);
        fieldSetFlags()[1] = true;
      }
      this.messageEventTypeBuilder = null;
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.Integer getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.kafka.course.avro.EventMessage.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.kafka.course.avro.EventMessage.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'messageEventType' field.
      * @return The value.
      */
    public com.kafka.course.avro.MessageEventType getMessageEventType() {
      return messageEventType;
    }

    /**
      * Sets the value of the 'messageEventType' field.
      * @param value The value of 'messageEventType'.
      * @return This builder.
      */
    public com.kafka.course.avro.EventMessage.Builder setMessageEventType(com.kafka.course.avro.MessageEventType value) {
      validate(fields()[1], value);
      this.messageEventTypeBuilder = null;
      this.messageEventType = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'messageEventType' field has been set.
      * @return True if the 'messageEventType' field has been set, false otherwise.
      */
    public boolean hasMessageEventType() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'messageEventType' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.kafka.course.avro.MessageEventType.Builder getMessageEventTypeBuilder() {
      if (messageEventTypeBuilder == null) {
        if (hasMessageEventType()) {
          setMessageEventTypeBuilder(com.kafka.course.avro.MessageEventType.newBuilder(messageEventType));
        } else {
          setMessageEventTypeBuilder(com.kafka.course.avro.MessageEventType.newBuilder());
        }
      }
      return messageEventTypeBuilder;
    }

    /**
     * Sets the Builder instance for the 'messageEventType' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.kafka.course.avro.EventMessage.Builder setMessageEventTypeBuilder(com.kafka.course.avro.MessageEventType.Builder value) {
      clearMessageEventType();
      messageEventTypeBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'messageEventType' field has an active Builder instance
     * @return True if the 'messageEventType' field has an active Builder instance
     */
    public boolean hasMessageEventTypeBuilder() {
      return messageEventTypeBuilder != null;
    }

    /**
      * Clears the value of the 'messageEventType' field.
      * @return This builder.
      */
    public com.kafka.course.avro.EventMessage.Builder clearMessageEventType() {
      messageEventType = null;
      messageEventTypeBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EventMessage build() {
      try {
        EventMessage record = new EventMessage();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        if (messageEventTypeBuilder != null) {
          record.messageEventType = this.messageEventTypeBuilder.build();
        } else {
          record.messageEventType = fieldSetFlags()[1] ? this.messageEventType : (com.kafka.course.avro.MessageEventType) defaultValue(fields()[1]);
        }
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EventMessage>
    WRITER$ = (org.apache.avro.io.DatumWriter<EventMessage>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EventMessage>
    READER$ = (org.apache.avro.io.DatumReader<EventMessage>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
