/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.kafka.course.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class MessageEventType extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5934050156489743211L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MessageEventType\",\"namespace\":\"com.kafka.course.avro\",\"fields\":[{\"name\":\"message\",\"type\":\"string\"},{\"name\":\"addressee\",\"type\":\"string\"},{\"name\":\"sender\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MessageEventType> ENCODER =
      new BinaryMessageEncoder<MessageEventType>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MessageEventType> DECODER =
      new BinaryMessageDecoder<MessageEventType>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<MessageEventType> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<MessageEventType> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<MessageEventType>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this MessageEventType to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a MessageEventType from a ByteBuffer. */
  public static MessageEventType fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence message;
  @Deprecated public java.lang.CharSequence addressee;
  @Deprecated public java.lang.CharSequence sender;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MessageEventType() {}

  /**
   * All-args constructor.
   * @param message The new value for message
   * @param addressee The new value for addressee
   * @param sender The new value for sender
   */
  public MessageEventType(java.lang.CharSequence message, java.lang.CharSequence addressee, java.lang.CharSequence sender) {
    this.message = message;
    this.addressee = addressee;
    this.sender = sender;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return message;
    case 1: return addressee;
    case 2: return sender;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: message = (java.lang.CharSequence)value$; break;
    case 1: addressee = (java.lang.CharSequence)value$; break;
    case 2: sender = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'message' field.
   * @return The value of the 'message' field.
   */
  public java.lang.CharSequence getMessage() {
    return message;
  }

  /**
   * Sets the value of the 'message' field.
   * @param value the value to set.
   */
  public void setMessage(java.lang.CharSequence value) {
    this.message = value;
  }

  /**
   * Gets the value of the 'addressee' field.
   * @return The value of the 'addressee' field.
   */
  public java.lang.CharSequence getAddressee() {
    return addressee;
  }

  /**
   * Sets the value of the 'addressee' field.
   * @param value the value to set.
   */
  public void setAddressee(java.lang.CharSequence value) {
    this.addressee = value;
  }

  /**
   * Gets the value of the 'sender' field.
   * @return The value of the 'sender' field.
   */
  public java.lang.CharSequence getSender() {
    return sender;
  }

  /**
   * Sets the value of the 'sender' field.
   * @param value the value to set.
   */
  public void setSender(java.lang.CharSequence value) {
    this.sender = value;
  }

  /**
   * Creates a new MessageEventType RecordBuilder.
   * @return A new MessageEventType RecordBuilder
   */
  public static com.kafka.course.avro.MessageEventType.Builder newBuilder() {
    return new com.kafka.course.avro.MessageEventType.Builder();
  }

  /**
   * Creates a new MessageEventType RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MessageEventType RecordBuilder
   */
  public static com.kafka.course.avro.MessageEventType.Builder newBuilder(com.kafka.course.avro.MessageEventType.Builder other) {
    return new com.kafka.course.avro.MessageEventType.Builder(other);
  }

  /**
   * Creates a new MessageEventType RecordBuilder by copying an existing MessageEventType instance.
   * @param other The existing instance to copy.
   * @return A new MessageEventType RecordBuilder
   */
  public static com.kafka.course.avro.MessageEventType.Builder newBuilder(com.kafka.course.avro.MessageEventType other) {
    return new com.kafka.course.avro.MessageEventType.Builder(other);
  }

  /**
   * RecordBuilder for MessageEventType instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MessageEventType>
    implements org.apache.avro.data.RecordBuilder<MessageEventType> {

    private java.lang.CharSequence message;
    private java.lang.CharSequence addressee;
    private java.lang.CharSequence sender;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.kafka.course.avro.MessageEventType.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.message)) {
        this.message = data().deepCopy(fields()[0].schema(), other.message);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.addressee)) {
        this.addressee = data().deepCopy(fields()[1].schema(), other.addressee);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.sender)) {
        this.sender = data().deepCopy(fields()[2].schema(), other.sender);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing MessageEventType instance
     * @param other The existing instance to copy.
     */
    private Builder(com.kafka.course.avro.MessageEventType other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.message)) {
        this.message = data().deepCopy(fields()[0].schema(), other.message);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.addressee)) {
        this.addressee = data().deepCopy(fields()[1].schema(), other.addressee);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.sender)) {
        this.sender = data().deepCopy(fields()[2].schema(), other.sender);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'message' field.
      * @return The value.
      */
    public java.lang.CharSequence getMessage() {
      return message;
    }

    /**
      * Sets the value of the 'message' field.
      * @param value The value of 'message'.
      * @return This builder.
      */
    public com.kafka.course.avro.MessageEventType.Builder setMessage(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.message = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'message' field has been set.
      * @return True if the 'message' field has been set, false otherwise.
      */
    public boolean hasMessage() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'message' field.
      * @return This builder.
      */
    public com.kafka.course.avro.MessageEventType.Builder clearMessage() {
      message = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'addressee' field.
      * @return The value.
      */
    public java.lang.CharSequence getAddressee() {
      return addressee;
    }

    /**
      * Sets the value of the 'addressee' field.
      * @param value The value of 'addressee'.
      * @return This builder.
      */
    public com.kafka.course.avro.MessageEventType.Builder setAddressee(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.addressee = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'addressee' field has been set.
      * @return True if the 'addressee' field has been set, false otherwise.
      */
    public boolean hasAddressee() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'addressee' field.
      * @return This builder.
      */
    public com.kafka.course.avro.MessageEventType.Builder clearAddressee() {
      addressee = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'sender' field.
      * @return The value.
      */
    public java.lang.CharSequence getSender() {
      return sender;
    }

    /**
      * Sets the value of the 'sender' field.
      * @param value The value of 'sender'.
      * @return This builder.
      */
    public com.kafka.course.avro.MessageEventType.Builder setSender(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.sender = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'sender' field has been set.
      * @return True if the 'sender' field has been set, false otherwise.
      */
    public boolean hasSender() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'sender' field.
      * @return This builder.
      */
    public com.kafka.course.avro.MessageEventType.Builder clearSender() {
      sender = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MessageEventType build() {
      try {
        MessageEventType record = new MessageEventType();
        record.message = fieldSetFlags()[0] ? this.message : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.addressee = fieldSetFlags()[1] ? this.addressee : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.sender = fieldSetFlags()[2] ? this.sender : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MessageEventType>
    WRITER$ = (org.apache.avro.io.DatumWriter<MessageEventType>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MessageEventType>
    READER$ = (org.apache.avro.io.DatumReader<MessageEventType>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
